### ISSUE TITLE
Specific Room Spawns Bug

### ISSUE THREAD

**Issue by DinoNuggets2** [steven4547466/Advanced-Subclassing-Redux#4]
When setting a specific spawn location (room type), it doesn't seem to spawn the subclass in that room if they also have a custom scale enabled.
I attached a video to show what it's doing, the scale is 1.19 for x, y, and z.
It isn't a big issue, I just wanted to make this so it can get fixed eventually.

https://user-images.githubusercontent.com/91291118/167077480-bf3d25da-6c55-4918-96a7-335d0acf6803.mp4

**Comment by steven4547466** [comment]
Although I can't say for sure what caused this, I have used scales before with spawn locations. I did release a few new updates today before I saw this that might help. Because of this I'm going to close this issue, but if it still happens, just reopen this issue and I'll look into it.
